api_base: "/v1"
deployment_config:
  - deployment_name: "yuehuang-gpt-4"
    model_name: "gpt-4-1106-preview"
    endpoint: "https://yuehuang.openai.azure.com/"
    api_key: "0bdff7a6d75349b7879fa6f0787fdd4c"
    api_version: "2023-03-15-preview"
  - deployment_name: "yuehuang-gpt-4"
    model_name: "gpt-4-0125-preview"
    endpoint: "https://yuehuang-india.openai.azure.com/"
    api_key: "964c0815812e4dd7b8d1fa44ac0a75e6"
    api_version: "2023-03-15-preview"
  - deployment_name: "TrustLLM_chatgpt_1106"
    model_name: "gpt-3.5-turbo"
    endpoint: "https://trustllm-gpt-4.openai.azure.com/"
    api_key: "1f462c580d06407eb49954553ab22ff7"
    api_version: "2023-03-15-preview"
  - deployment_name: "TrustLLM-embedding"
    model_name: "text-embedding-ada-002"
    endpoint: "https://trustllm-gpt-4.openai.azure.com/"
    api_key: "1f462c580d06407eb49954553ab22ff7"
    api_version: "2023-03-15-preview"

